### ISSUE TITLE
changing a file name/cut and paste file to different directory does not relad

### ISSUE THREAD

**Issue by damianatorrpm** [lxqt/libfm-qt#510] opened 2020-01-11 23:00 UTC
##### Expected Behavior
have the search results up-to-date with edited file names and or remove files removed

##### Current Behavior
changing a file name or cut and paste file to different directory does not reload if you do this from 
within search:/// results

##### Possible Solution
TBD

**Comment by tsujan** [comment] 2020-01-11 23:47
Correct. Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/491

**Closed by tsujan** 2020-01-11 23:47 UTC
