### ISSUE TITLE
File Properties windows open behind and stay behind File Dialog

### ISSUE THREAD

**Issue by bbigam** [lxqt/libfm-qt#981] opened 2024-05-29 23:25 UTC
When right clicking a file or folder in the LXQt File Dialog and selecting Properties, the File Properties window opens behind the File Dialog, and can't be brought to the front.

##### Expected Behavior
I would expect the File Properties window to open in front of the File Dialog, since I opened it from the File Dialog.

##### Current Behavior
The above behavior happens in any app I try that uses the LXQt File Dialog, every time. Tested in both QT5 and QT6 apps. Clicking in the Properties window does not bring it to the front. Clicking on buttons within the Properties window doesn't work, either; even the close button doesn't work, so the dialog can't be dismissed. The window can be moved.
Once the File Dialog is dismissed, the File Properties window works as expected.

##### Possible Solution
I don't know anything about the coding, but the expected behavior would put the properties window in front of the window it was opened from, in this case, the file dialog.
I wonder whether this issue would need to be fixed in both libfm-qt-1.4.x and libfm-qt6-2.0.x, since it happens in both qt5 and qt6 apps - if this is the right package for the issue anyway.

##### Steps to Reproduce (for bugs)
1.  Open any app that uses the LXQt File Dialog
2.  Invoke the dialog as if to open a file
3.  Right-click on any file or folder in the main part of the window, and click Properties.
4.  Results as described above.

##### Context
The File Properties window is not useful if it can't be seen. It's inconvenient to have to drag windows around every time to get them side-by-side, when it was expected to be in the front. It can't be interacted with, either, or even dismissed, until after dismissing the file dialog.

##### System Information
* Distribution & Version: OpenSUSE Tumbleweed 20240524, with X11:LXQT staging repo for LXQt 2.0 (https://build.opensuse.org/project/show/X11:LXQt)
* Kernel: 6.9.1
* Qt Version: 6.7.0
* libqtxdg Version: libqt5xdg-3.12 and libqt6xdg-4.0.0
* lxqt-build-tools Version: n/a
* Package version: libfm-qt-1.4.0 and libfm-qt6-2.0.2

Note: the staging repo is not providing co-installable lxqt-qtplugin for qt5 and qt6, but I have them. qtplugin-2.0.0 from the staging repo, and qtplugin-1.4.1 from the main repo; I manually installed the binary from 1.4.1 by downloading the rpm, extracting the files, and sudo cp-ing the binary into place, and it works perfectly.

This is my first participation in the LXQt Github project, so if I've missed something or posted the bug in the wrong place, please gently help me get it right.

**Comment by tsujan** [comment] 2024-05-29 23:52
It has never happened to me but, although I'm one of libfm-qt's developers, my case doesn't count. Long story made short, I always apply a small patch for it, and I always forget to make a PR with it ;) It's time to make that PR, perhaps after another LXQt member confirms your report.

Thanks for reporting!

**Comment by tsujan** [comment] 2024-05-30 00:02
Made the PR here: https://github.com/lxqt/libfm-qt/pull/982

**Comment by bbigam** [comment] 2024-05-30 00:37
Whoa, that was quick! I guess since you've been sitting on the patch. :-)
Will it need to be applied separately to the qt5 build of libfm-qt?

**Comment by tsujan** [comment] 2024-05-30 01:01
> Will it need to be applied separately to the qt5 build of libfm-qt?

In LXQt, old branches aren't developed or patched, but you could apply the patch to libfm-qt-1.4.0 (or even older versions) too.

The patch will be applied to git and will be in the next stable version once merged.

That being said, and although I can't reproduce your reported issue with the patch, we need either another LXQt member or an LXQt user (like you) to confirm that the problem is fixed by it, because we aren't sure that the problem isn't caused by the window manager you use.

**Comment by bbigam** [comment] 2024-05-30 01:23
Got it.
Honestly, I don't know how to build from source. If there's a simple, easy
way, or if you provide a binary, I'd test it.

**Comment by stefonarch** [comment] 2024-05-30 04:43
I just can't reproduce it -properties window opened from filedialog is always in front with openbox, xfwm4, kwin and labwc on wayland with featherpad. But while writing this I tested in firefox and yes, it''s below with xfwm4 and openbox but below the firefox window.

**Comment by stefonarch** [comment] 2024-05-30 07:31
Back on labwc and the patch seems working in firefox/thunderbird. Retested with x11 and it's ok too. Rechecked with libfm-qt master and it's broken again. Looks like the portal thing needs relogin, restarting firefox isn't enough.

**Comment by bbigam** [comment] 2024-05-30 11:06
I'll mention that I'm using Openbox.
Had the problem with lximage-qt, VLC, and Firefox (portal), and anything
else I tried.

**Comment by stefonarch** [comment] 2024-05-30 11:44
It doesn't look to be related to window managers in my tests, but  I tested only with featherpad and firefox.

**Comment by tsujan** [comment] 2024-05-30 12:23
Thanks for the tests!

> Looks like the portal thing needs relogin, restarting firefox isn't enough.

That may be related to how the portal works. As someone who has always had the patch, I don't see any issue in Firefox and Chromium either. Your tests also show that.

**Closed** 2024-05-30 12:23 UTC
