### ISSUE TITLE
pcmanfm-qt does not start as root on live isos

### ISSUE THREAD

**Issue by adrian15** [lxqt/libfm-qt#427] opened 2019-05-10 23:26 UTC
It does not start - without a meaningful message

**Expected Behavior**

it should start as root

**Current Behavior**

It does not start at all as root

**Possible Solution**

No idea yet.

**Steps to Reproduce (for bugs)**

* Get a live ISO (siduction, manjaro, debian buster)
* Start and open a terminal
```
lx(sudo) pcmanfm-qt
```
* lxsudo ends and no window appears

**Context**

I want ot use pcmanfm-qt as root even on live isos - not possible

**System Information**

latest release

**Additional information**

Original bug https://github.com/lxqt/pcmanfm-qt/issues/958 was filed in pcmanfm-qt.

**Comment by tsujan** [comment] 2019-05-10 23:27
duplicate of https://github.com/lxqt/pcmanfm-qt/issues/774

**Closed by tsujan** 2019-05-10 23:27 UTC
